import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { ThemeModeScript } from 'flowbite-react';

import { robotoMedium } from '@/font/font';

export const metadata: Metadata = {
    title: {
        template: '%s | first-next',
        default: 'first-next'
    },
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <ThemeModeScript />
            </head>
            <body className={`${robotoMedium.className} antialiased`}>{children}</body>
        </html>
    );
}
