import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { ThemeModeScript } from 'flowbite-react';

import { robotoMedium } from '@/font/font';
import { AlertBox } from '@/component/elements/message-box';
import { MenuNavbar } from '@/component/header/nav';
import InitUser from '@/component/elements/init-user';

export const metadata: Metadata = {
    title: {
        template: '%s | first-next',
        default: 'first-next'
    },
    description: 'Generated by create next app'
};

export const dynamic = 'force-static';

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <ThemeModeScript />
            </head>
            <body className={`${robotoMedium.className} antialiased`}>
                <InitUser />
                <MenuNavbar />
                <AlertBox />
                {children}
            </body>
        </html>
    );
}
